-- Align Supabase public.blogs with the current BlogrXiv project state.
-- Generated from admin/blogs-supabase-import.csv.
-- Current local corpus: 593 published blogs.
-- Expected category counts: {"Research Craft":46,"AI Agents":70,"LLM & MLLM":42,"Trustworthy AI":74,"Efficient AI":60,"Visual Generation":95,"Multimodal Model":77,"Foundation Model":33,"World Model":47,"How to Research":7,"Frontier":42}

begin;

-- Remove the old taxonomy constraint before normalizing existing rows.
alter table public.blogs
drop constraint if exists blogs_category_check;

-- Keep this delete as an idempotent safeguard for the removed local post.
delete from public.blogs
where id = 'complex-systems-visualizer';

-- Apply the current project taxonomy to every local blog id.
with updates(id, category) as (
  values
  ('iclr2026-why-ai-evaluations-need-error-bars', 'Research Craft'),
  ('iclr2026-web-agent', 'AI Agents'),
  ('iclr2026-wait-do-we-need-to-wait', 'LLM & MLLM'),
  ('iclr2026-vis-llm-latent-geometry', 'Trustworthy AI'),
  ('iclr2026-useful-calibrated-uncertainties', 'Trustworthy AI'),
  ('iclr2026-unigramlm-manual', 'LLM & MLLM'),
  ('iclr2026-trade-offs-in-llm-compute-for-reasoning-intensive-information-retrieval', 'Efficient AI'),
  ('iclr2026-tracing-principles-behind-modern-diffusion-models', 'Visual Generation'),
  ('iclr2026-the-evolution-of-flashattention', 'Efficient AI'),
  ('iclr2026-style-representations', 'Visual Generation'),
  ('iclr2026-spatial-awareness', 'Multimodal Model'),
  ('iclr2026-sparsity', 'Efficient AI'),
  ('iclr2026-rl-with-gnns', 'AI Agents'),
  ('iclr2026-revisiting-the-nle', 'AI Agents'),
  ('iclr2026-rethinking-diffusion-langevin', 'Visual Generation'),
  ('iclr2026-recur-refine-reason', 'LLM & MLLM'),
  ('iclr2026-probabilistic-circuits-for-uncertainty-quantification', 'Trustworthy AI'),
  ('iclr2026-precision-extraction', 'Research Craft'),
  ('iclr2026-ppo-batch-size', 'AI Agents'),
  ('iclr2026-polar-svd', 'Efficient AI'),
  ('iclr2026-performative-prediction', 'Trustworthy AI'),
  ('iclr2026-nlp-for-human-sciences', 'Research Craft'),
  ('iclr2026-model-misspecification-in-sbi', 'Research Craft'),
  ('iclr2026-mlip-practical', 'Foundation Model'),
  ('iclr2026-mislead-lm', 'Trustworthy AI'),
  ('iclr2026-misalign-failure-mode', 'Trustworthy AI'),
  ('iclr2026-loneliness-social-misalignment', 'Trustworthy AI'),
  ('iclr2026-llm-post-training', 'LLM & MLLM'),
  ('iclr2026-llm-bitter-lesson', 'Foundation Model'),
  ('iclr2026-layered-ontology-model', 'Trustworthy AI'),
  ('iclr2026-justrl', 'LLM & MLLM'),
  ('iclr2026-interpret-model', 'Trustworthy AI'),
  ('iclr2026-ideation-heuristics', 'Research Craft'),
  ('iclr2026-iclr-induction', 'Trustworthy AI'),
  ('iclr2026-generalization-in-diffusion-as-infinite-hvae', 'Visual Generation'),
  ('iclr2026-general-agent-evaluation', 'AI Agents'),
  ('iclr2026-genai-archaeology', 'Research Craft'),
  ('iclr2026-fractal-mas', 'AI Agents'),
  ('iclr2026-flow-where-you-want', 'Visual Generation'),
  ('iclr2026-flow-map-learning', 'Visual Generation'),
  ('iclr2026-fixing-bottlenecks-in-state-space-models', 'Efficient AI'),
  ('iclr2026-feature-reduction', 'Efficient AI'),
  ('iclr2026-economic-agents', 'AI Agents'),
  ('iclr2026-dllm', 'LLM & MLLM'),
  ('iclr2026-dissecting-non-determinism', 'Research Craft'),
  ('iclr2026-discretisation-invariance', 'Foundation Model'),
  ('iclr2026-diffusion-inverse-problems', 'Visual Generation'),
  ('iclr2026-diffusion-architecture-evolution', 'Visual Generation'),
  ('iclr2026-destruction', 'Visual Generation'),
  ('iclr2026-content-promotion-agent-design', 'AI Agents'),
  ('iclr2026-compositionality', 'Foundation Model'),
  ('iclr2026-chunked-tabpfn', 'Efficient AI'),
  ('iclr2026-budget-alignment', 'LLM & MLLM'),
  ('iclr2026-bits-over-random', 'Research Craft'),
  ('iclr2026-autoregressive-tokenization', 'LLM & MLLM'),
  ('iclr2026-an-overview-of-subliminal-learning', 'Trustworthy AI'),
  ('iclr2026-adversarial-conditioning-paradox', 'Trustworthy AI'),
  ('iclr2025-analytical-simulated-dynamics', 'Research Craft'),
  ('iclr2025-conditional-flow-matching', 'Visual Generation'),
  ('iclr2025-sparse-autodiff', 'Efficient AI'),
  ('iclr2025-analysing-the-spectral-biases-in-generative-models', 'Visual Generation'),
  ('iclr2025-opt-summary', 'Research Craft'),
  ('iclr2025-building-blocks-of-differentially-private-training', 'Trustworthy AI'),
  ('iclr2025-rethinking-llm-simulation', 'World Model'),
  ('iclr2025-pessa', 'Efficient AI'),
  ('iclr2025-do-not-write-jailbreak-papers', 'How to Research'),
  ('iclr2025-toddlers-vs-vismodels', 'Multimodal Model'),
  ('iclr2025-localization', 'Trustworthy AI'),
  ('iclr2025-factual-validation-simplification', 'Trustworthy AI'),
  ('iclr2025-fine-tuning-token-based-large-multimodal-models', 'Multimodal Model'),
  ('iclr2025-imagenet-flaws', 'Multimodal Model'),
  ('iclr2025-flow-with-what-you-know', 'Visual Generation'),
  ('iclr2025-interpret-classification', 'Foundation Model'),
  ('iclr2025-visualizing-training', 'Research Craft'),
  ('iclr2025-engram', 'Trustworthy AI'),
  ('iclr2025-feature-geometry', 'LLM & MLLM'),
  ('iclr2025-linrec', 'LLM & MLLM'),
  ('iclr2025-llm-democracy', 'Trustworthy AI'),
  ('iclr2025-lost-in-prediction', 'Foundation Model'),
  ('iclr2025-vlm-understanding', 'Trustworthy AI'),
  ('iclr2025-ebm-vs-mcmc', 'Visual Generation'),
  ('iclr2025-mad', 'AI Agents'),
  ('iclr2025-multimodal-learning', 'Multimodal Model'),
  ('iclr2025-llm-knowledge-distil', 'LLM & MLLM'),
  ('iclr2025-fisher', 'Efficient AI'),
  ('iclr2025-llm-context-utilization', 'LLM & MLLM'),
  ('iclr2025-risks-private-evals', 'Trustworthy AI'),
  ('iclr2025-pitfalls-of-evidence-based-ai-policy', 'Trustworthy AI'),
  ('iclr2025-positional-embedding', 'LLM & MLLM'),
  ('iclr2025-foundation-adapter', 'LLM & MLLM'),
  ('iclr2025-calibrated-mia', 'Trustworthy AI'),
  ('iclr2025-reexamining-the-aleatoric-and-epistemic-uncertainty-dichotomy', 'Trustworthy AI'),
  ('iclr2025-repurposing', 'AI Agents'),
  ('iclr2025-linear-gnn-convergence-restated', 'Research Craft'),
  ('iclr2025-rethinking-graph-prompts', 'Trustworthy AI'),
  ('iclr2025-spd', 'Trustworthy AI'),
  ('iclr2025-steering-llms-behavior', 'Trustworthy AI'),
  ('iclr2025-the-illustrated-alphafold', 'Multimodal Model'),
  ('iclr2025-the-lottery-llm-hyperthesis', 'LLM & MLLM'),
  ('iclr2025-towards-more-rigorous-llm-evals', 'Research Craft'),
  ('iclr2025-scalable-mcts', 'AI Agents'),
  ('iclr2025-calibration', 'Trustworthy AI'),
  ('iclr2025-pocp', 'LLM & MLLM'),
  ('iclr2025-anthropomorphic-ai', 'Trustworthy AI'),
  ('iclr2024-language-model-development-as-a-new-subfield', 'LLM & MLLM'),
  ('iclr2024-mode-switching', 'AI Agents'),
  ('iclr2024-dpi-fsvi', 'Foundation Model'),
  ('iclr2024-diffusion-theory-from-scratch', 'Visual Generation'),
  ('iclr2024-deqalg-reasoning', 'Research Craft'),
  ('iclr2024-double-descent-demystified', 'Foundation Model'),
  ('iclr2024-elaborating-on-the-value-of-flow-matching-for-density-estimation', 'Visual Generation'),
  ('iclr2024-exploring-meta-learned-curiosity-algorithms', 'AI Agents'),
  ('iclr2024-update-frequency-in-mbrl', 'World Model'),
  ('iclr2024-fairness-ai-two-phil-or-just-one', 'Trustworthy AI'),
  ('iclr2024-bench-hvp', 'Efficient AI'),
  ('iclr2024-primacy-bias-and-why-it-helps-to-forget', 'AI Agents'),
  ('iclr2024-alibi-mlm', 'LLM & MLLM'),
  ('iclr2024-clml', 'Foundation Model'),
  ('iclr2024-rlhf-without-rl', 'AI Agents'),
  ('iclr2024-hidden-convex-relu', 'Efficient AI'),
  ('iclr2024-the-n-implementation-details-of-rlhf-with-ppo', 'AI Agents'),
  ('iclr2024-robust-foundation-model', 'Trustworthy AI'),
  ('iclr2024-understanding-gradient-inversion-attacks-from-the-prior-knowledge-perspective', 'Trustworthy AI'),
  ('iclr2024-understanding-icl', 'LLM & MLLM'),
  ('iclr2024-unraveling-the-impact-of-training-samples', 'Foundation Model'),
  ('iclr2024-what-exactly-has-tabpfn-learned-to-do', 'LLM & MLLM'),
  ('iclr2023-hitchhikers-momentum', 'Efficient AI'),
  ('iclr2023-autoregressive-neural-pde-solver', 'LLM & MLLM'),
  ('iclr2023-facial-poisoning', 'Trustworthy AI'),
  ('iclr2023-adamw', 'Efficient AI'),
  ('iclr2023-how-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks', 'Foundation Model'),
  ('iclr2023-how-much-meta-learning-is-in-image-to-image-translation', 'Visual Generation'),
  ('iclr2023-bsuite-applications', 'AI Agents'),
  ('iclr2023-riit', 'AI Agents'),
  ('iclr2023-classification-layer-initialization-in-maml', 'Efficient AI'),
  ('iclr2023-raspy', 'LLM & MLLM'),
  ('iclr2023-sets-and-graphs', 'Foundation Model'),
  ('iclr2022-text-gen-via-lfd', 'AI Agents'),
  ('iclr2022-two-player-auction-learning', 'AI Agents'),
  ('iclr2022-lecun1989', 'Foundation Model'),
  ('iclr2022-zero-cost-proxies', 'Efficient AI'),
  ('iclr2022-non-monotonic-autoregressive-ordering', 'LLM & MLLM'),
  ('iclr2022-does-adam', 'Efficient AI'),
  ('iclr2022-euclidean-geometric-graph', 'Foundation Model'),
  ('iclr2022-conformation-generation', 'Visual Generation'),
  ('iclr2022-kgs', 'Foundation Model'),
  ('iclr2022-coarsening', 'Foundation Model'),
  ('iclr2022-looking-at-the-performer-from-a-hopfield-point-of-view', 'LLM & MLLM'),
  ('iclr2022-unnormalized-resnets', 'Foundation Model'),
  ('iclr2022-dyadic-fairness', 'Trustworthy AI'),
  ('iclr2022-pplm', 'LLM & MLLM'),
  ('iclr2022-deep-learning-for-routing-problems', 'AI Agents'),
  ('iclr2022-representation-change-in-model-agnostic-meta-learning', 'Efficient AI'),
  ('iclr2022-rethinking-valuedice', 'AI Agents'),
  ('iclr2022-emergent-symbols', 'Foundation Model'),
  ('iclr2022-ppo-implementation-details', 'AI Agents'),
  ('iclr2022-annotated-s4', 'LLM & MLLM'),
  ('iclr2022-understanding-mtr-meta', 'Foundation Model'),
  ('kalomaze-rl-for-knowledge-awareness', 'Trustworthy AI'),
  ('kalomaze-dont-exclude-rl-rollouts', 'AI Agents'),
  ('kalomaze-rl-learning-with-lora', 'Efficient AI'),
  ('kalomaze-understanding-transformers-beyond-math', 'Foundation Model'),
  ('kalomaze-grpo-judge-experiments', 'Trustworthy AI'),
  ('kalomaze-why-does-grpo-work', 'AI Agents'),
  ('kalomaze-synthetic-rejected-preference-data', 'Trustworthy AI'),
  ('openai-separating-signal-from-noise-coding-evaluations', 'Research Craft'),
  ('openai-gpt-5-6', 'Frontier'),
  ('openai-gpt-red-self-improvement-robustness', 'Trustworthy AI'),
  ('kimi-k3-open-frontier-intelligence', 'Frontier'),
  ('thinking-machines-inkling-open-weights-model', 'Frontier'),
  ('thinking-machines-replicate-expert-judgment-finance', 'Efficient AI'),
  ('finite-time-nonsmooth-signum-muon', 'Efficient AI'),
  ('openai-deployment-simulation', 'Frontier'),
  ('google-machine-unlearning-audit', 'Trustworthy AI'),
  ('google-agentic-rag-sufficient-context', 'Frontier'),
  ('huggingface-olmo-eval-workbench', 'Research Craft'),
  ('sebastian-llm-architecture-kv-compression', 'Foundation Model'),
  ('huggingface-continuous-batching-async', 'Efficient AI'),
  ('google-reasoningbank-agent-memory', 'AI Agents'),
  ('bai-verbalization-overinterpretation', 'Trustworthy AI'),
  ('nvidia-scaling-video-training-parallelism', 'Visual Generation'),
  ('yoonho-text-optimization-seriously', 'AI Agents'),
  ('tilde-compositional-steepest-descent', 'Efficient AI'),
  ('openathena-pretraining-efficiency', 'Efficient AI'),
  ('luke-huang-frontier-asynchronous-rl', 'AI Agents'),
  ('yichuan-rl-as-a-service-infrastructure', 'AI Agents'),
  ('galilai-stable-worldmodel', 'World Model'),
  ('hylak-how-to-eval-ai-agents', 'Research Craft'),
  ('davies-ai-agent-evaluation-frameworks', 'Research Craft'),
  ('priyal-mechanics-of-lora', 'Efficient AI'),
  ('xuhui-thinking-in-rl', 'AI Agents'),
  ('chinmay-policy-distillation-imitation-game', 'Efficient AI'),
  ('openai-macro-evals-agentic-systems', 'Research Craft'),
  ('shreya-agent-assisted-qualitative-analysis', 'How to Research'),
  ('sakana-diffusionblocks', 'Efficient AI'),
  ('aleksa-transformer-life-token', 'Foundation Model'),
  ('greg-goal-engineering', 'AI Agents'),
  ('jiaxin-generalization-dynamics', 'Foundation Model'),
  ('trajectory-multi-lora-continual-learning', 'Efficient AI'),
  ('roy-anatomy-of-an-llm', 'LLM & MLLM'),
  ('perplexity-unigram-tokenizer-cpu', 'Efficient AI'),
  ('howard-spectral-progressive-diffusion', 'Visual Generation'),
  ('dair-context-engineering-guide', 'AI Agents'),
  ('yao-fu-gpt-ability-sources', 'LLM & MLLM'),
  ('google-palm-scaling-pathways', 'Frontier'),
  ('sergey-levine-offline-rl-made-easier', 'AI Agents'),
  ('patrick-mineault-good-research-code', 'How to Research'),
  ('transformer-circuits-mathematical-framework', 'Trustworthy AI'),
  ('sara-hooker-hardware-lottery', 'Efficient AI'),
  ('francois-chollet-llm-prompt-engineering', 'LLM & MLLM'),
  ('francois-chollet-limitations-deep-learning', 'Foundation Model'),
  ('david-ha-weight-agnostic-networks', 'Efficient AI'),
  ('david-ha-world-models-experiments', 'World Model'),
  ('karpathy-recipe-training-neural-networks', 'How to Research'),
  ('karpathy-unreasonable-rnns', 'Foundation Model'),
  ('colah-understanding-lstms', 'Foundation Model'),
  ('anthropic-managed-agents', 'AI Agents'),
  ('anthropic-harness-design-long-running-apps', 'AI Agents'),
  ('anthropic-eval-awareness-browsecomp', 'Trustworthy AI'),
  ('openai-codex-agent-loop', 'AI Agents'),
  ('anthropic-demystifying-evals-agents', 'Research Craft'),
  ('anthropic-ai-resistant-technical-evaluations', 'Research Craft'),
  ('cursor-secure-codebase-indexing', 'AI Agents'),
  ('anthropic-bloom-auto-evals', 'Trustworthy AI'),
  ('anthropic-effective-harnesses-long-running-agents', 'AI Agents'),
  ('anthropic-code-execution-with-mcp', 'AI Agents'),
  ('anthropic-claude-code-sandboxing', 'Trustworthy AI'),
  ('anthropic-writing-tools-for-agents', 'AI Agents'),
  ('braintrust-logs-evals-same-place', 'Research Craft'),
  ('cursor-dynamic-context-discovery', 'AI Agents'),
  ('hf-continuous-batching-from-first-principles', 'Efficient AI'),
  ('baseten-kv-cache-aware-routing', 'Efficient AI'),
  ('hf-colpali-visual-document-retrieval', 'Multimodal Model'),
  ('jina-late-chunking-contextual-retrieval', 'Research Craft'),
  ('metr-frontier-risk-report-2026', 'Frontier'),
  ('claude-code-large-codebases', 'Research Craft'),
  ('goodfire-interpreting-language-model-parameters', 'Trustworthy AI'),
  ('langchain-autonomous-context-compression', 'AI Agents'),
  ('cognition-uses-devin-to-build-devin', 'AI Agents'),
  ('goodfire-interpretability-infra-frontier-scale', 'Efficient AI'),
  ('goodfire-features-as-rewards-rlfr', 'Trustworthy AI'),
  ('metr-time-horizon-claude-code-codex', 'Research Craft'),
  ('metr-time-horizon-1-1', 'Trustworthy AI'),
  ('metr-early-monitorability-evaluations', 'Trustworthy AI'),
  ('apollo-science-of-scheming', 'Trustworthy AI'),
  ('apollo-loss-of-control-playbook', 'Trustworthy AI'),
  ('langchain-building-langgraph-runtime', 'AI Agents'),
  ('manus-context-engineering-agents', 'AI Agents'),
  ('cognition-dont-build-multi-agents', 'AI Agents'),
  ('transformer-circuits-circuit-tracing', 'Trustworthy AI'),
  ('vllm-pagedattention-serving', 'Efficient AI'),
  ('hf-rl-environments-guide', 'Research Craft'),
  ('leap-exemplar-partitioning', 'Trustworthy AI'),
  ('goodfire-world-inside-neural-networks', 'Trustworthy AI'),
  ('openai-accidental-cot-grading', 'Trustworthy AI'),
  ('openai-monitorability-evals-release', 'Trustworthy AI'),
  ('lesswrong-review-accidental-cot-grading', 'Trustworthy AI'),
  ('anthropic-natural-language-autoencoders', 'Trustworthy AI'),
  ('transformer-circuits-natural-language-autoencoders', 'Trustworthy AI'),
  ('sander-flow-maps', 'Visual Generation'),
  ('dylan-faulty-memory-agents', 'AI Agents'),
  ('pythagorai-cost-ai-agents', 'AI Agents'),
  ('tufa-enhancing-reasoning-small-language-models', 'LLM & MLLM'),
  ('nrehiew-minimal-editing', 'Research Craft'),
  ('anthropic-introspection-adapters', 'Trustworthy AI'),
  ('iclr-mdp-to-gcmdp', 'AI Agents'),
  ('nvidia-emerging-optimizers-megatron', 'Efficient AI'),
  ('a16z-continual-learning', 'Foundation Model'),
  ('ryan-briggs-research-adjudication', 'How to Research'),
  ('thoughtful-posttrainbench', 'Research Craft'),
  ('patrick-diffusion-eval-methodology', 'Research Craft'),
  ('anyscale-llm-post-training-skill', 'AI Agents'),
  ('thoughtful-letting-ai-posttrain-ai', 'How to Research'),
  ('aiowls-stochastic-self-stabilization', 'Efficient AI'),
  ('noah-pedagogical-rl', 'LLM & MLLM'),
  ('deepwiki-mimo-v2-flash', 'Frontier'),
  ('emergentmind-mopd', 'LLM & MLLM'),
  ('goodfire-optimism-interpretability', 'Trustworthy AI'),
  ('geeksforgeeks-knowledge-representation-ai', 'Foundation Model'),
  ('openai-parameter-golf', 'How to Research'),
  ('openai-cot-monitorability', 'Trustworthy AI'),
  ('modal-host-overhead-inference', 'Efficient AI'),
  ('deepmind-codemender-security', 'Trustworthy AI'),
  ('nvidia-ai-red-team-security-advice', 'Trustworthy AI'),
  ('anthropic-context-engineering-agents', 'AI Agents'),
  ('hf-smollm3-recipe', 'Foundation Model'),
  ('anthropic-agentic-misalignment', 'Trustworthy AI'),
  ('apollo-in-context-scheming-2025', 'Trustworthy AI'),
  ('simon-lethal-trifecta-agents', 'Trustworthy AI'),
  ('anthropic-multi-agent-research-system', 'AI Agents'),
  ('humanlayer-12-factor-agents', 'AI Agents'),
  ('metr-long-task-horizon', 'Trustworthy AI'),
  ('hf-ultrascale-playbook', 'Efficient AI'),
  ('anthropic-alignment-faking', 'Trustworthy AI'),
  ('hf-fineweb-data-curation', 'Foundation Model'),
  ('rdi-agent-benchmarks-broken', 'Trustworthy AI'),
  ('interconnects-open-models-mid-2026', 'Frontier'),
  ('rdi-benchmark-100-percent', 'Trustworthy AI'),
  ('rdi-opensage-agent-engine', 'AI Agents'),
  ('hamel-evals-skills-coding-agents', 'Research Craft'),
  ('interconnects-open-models-next-phase', 'Frontier'),
  ('hamel-llm-evals-faq', 'Research Craft'),
  ('interconnects-use-multiple-models', 'Research Craft'),
  ('interconnects-state-open-models-2025', 'Frontier'),
  ('rdi-cybergym-agent-security', 'Trustworthy AI'),
  ('stanford-medagentbench', 'Research Craft'),
  ('hamel-inspect-ai-evals', 'Trustworthy AI'),
  ('interconnects-next-gen-reasoners', 'LLM & MLLM'),
  ('stanford-simulating-human-behavior', 'AI Agents'),
  ('stanford-ai-index-2025', 'Frontier'),
  ('stanford-nnetnav-web-agent', 'AI Agents'),
  ('interconnects-rl-renaissance', 'LLM & MLLM'),
  ('interconnects-reasoning-generalize', 'LLM & MLLM'),
  ('jay-illustrated-deepseek-r1', 'Frontier'),
  ('hamel-llm-judge-guide', 'Research Craft'),
  ('hamel-ai-product-needs-evals', 'Research Craft'),
  ('mlm-agentic-programming-roadmap', 'AI Agents'),
  ('cmu-vlm-speak-cinema', 'Multimodal Model'),
  ('mlm-agentic-design-patterns', 'AI Agents'),
  ('mlm-llm-observability-tools', 'Research Craft'),
  ('mlm-prompt-compression-agentic-costs', 'Efficient AI'),
  ('sebastian-coding-agent-components', 'AI Agents'),
  ('sebastian-visual-attention-variants', 'Efficient AI'),
  ('cmu-ai-step-aside', 'AI Agents'),
  ('cmu-lumberchunker', 'LLM & MLLM'),
  ('sebastian-inference-time-scaling-categories', 'LLM & MLLM'),
  ('sebastian-state-llms-2025', 'Frontier'),
  ('spaces-deltanet-l2-normalize', 'Efficient AI'),
  ('cmu-llm-judge-rating-indeterminacy', 'Research Craft'),
  ('spaces-weight-decay-learning-rate', 'Efficient AI'),
  ('sebastian-deepseek-v32-architecture', 'Frontier'),
  ('cmu-llm-rl-hard-problems', 'LLM & MLLM'),
  ('spaces-diffusion-predict-data', 'Visual Generation'),
  ('spaces-muon-guide', 'Efficient AI'),
  ('sebastian-llm-evaluation-4-approaches', 'Research Craft'),
  ('cmu-verlog-multiturn-rl-agents', 'AI Agents'),
  ('sebastian-big-llm-architecture-comparison', 'Foundation Model'),
  ('xunhuang-video-world-models', 'World Model'),
  ('sebastian-kv-cache-from-scratch', 'Efficient AI'),
  ('cmu-test-time-compute-meta-rl', 'LLM & MLLM'),
  ('lilian-extrinsic-hallucinations', 'Trustworthy AI'),
  ('lilian-diffusion-video-generation', 'Visual Generation'),
  ('lilian-human-data-quality', 'Research Craft'),
  ('thinking-machines-interaction-models', 'Frontier'),
  ('dao-sonicmoe-blackwell', 'Efficient AI'),
  ('dao-gram-newton-schulz', 'Efficient AI'),
  ('dao-mamba3-methods', 'Efficient AI'),
  ('dao-flashattention-4', 'Efficient AI'),
  ('simon-5-minute-llms-2026', 'Frontier'),
  ('claude-opus-47', 'Frontier'),
  ('decoupled-diloco', 'Efficient AI'),
  ('hf-state-open-source-ai-spring-2026', 'Frontier'),
  ('simon-year-in-llms-2025', 'Frontier'),
  ('thinking-machines-tinker-ga', 'Research Craft'),
  ('eugene-product-evals', 'Research Craft'),
  ('jose-muon-optimizer-explained', 'Efficient AI'),
  ('thinking-machines-tinker', 'Research Craft'),
  ('thinking-machines-nondeterminism', 'Efficient AI'),
  ('openai-why-lms-hallucinate', 'Trustworthy AI'),
  ('allenai-critical-batch-size', 'Efficient AI'),
  ('eugene-long-context-qa-evals', 'Research Craft'),
  ('claude-4', 'Frontier'),
  ('alphaevolve-coding-agent', 'Frontier'),
  ('lilian-why-we-think', 'LLM & MLLM'),
  ('openai-o3-o4-mini', 'LLM & MLLM'),
  ('anthropic-tracing-thoughts', 'Trustworthy AI'),
  ('openai-agent-tools-2025', 'AI Agents'),
  ('jeremy-deriving-muon', 'Efficient AI'),
  ('claude-37-sonnet-code', 'Frontier'),
  ('sebastian-reasoning-llms', 'LLM & MLLM'),
  ('open-r1', 'Frontier'),
  ('vllm-v1-core-architecture', 'Efficient AI'),
  ('chip-ai-engineering-pitfalls', 'Research Craft'),
  ('building-effective-agents', 'AI Agents'),
  ('keller-muon-optimizer', 'Efficient AI'),
  ('smolagents', 'AI Agents'),
  ('model-context-protocol', 'AI Agents'),
  ('lilian-reward-hacking', 'Trustworthy AI'),
  ('olmo2-open-language-model', 'Frontier'),
  ('tulu3-open-post-training', 'Foundation Model'),
  ('flexattention', 'Efficient AI'),
  ('llama-31-open-source-ai', 'Frontier'),
  ('smollm-small-language-models', 'Efficient AI'),
  ('flashattention-3', 'Efficient AI'),
  ('gemma-2-open-models', 'Frontier'),
  ('applied-llms-lessons', 'Research Craft'),
  ('eugene-llm-evals', 'Research Craft'),
  ('cosmopedia-synthetic-data', 'Foundation Model'),
  ('sglang-radixattention', 'Efficient AI'),
  ('simon-llms-in-2024', 'Frontier'),
  ('ovis25', 'Multimodal Model'),
  ('bitvla', 'World Model'),
  ('step-video-ti2v', 'Visual Generation'),
  ('hunyuanvideo-i2v', 'Visual Generation'),
  ('step-video-t2v', 'Visual Generation'),
  ('qvq-72b-preview', 'Frontier'),
  ('internvl25', 'Multimodal Model'),
  ('open-sora-plan', 'Frontier'),
  ('allegro-video', 'Visual Generation'),
  ('aria-moe', 'Multimodal Model'),
  ('omnigen', 'Visual Generation'),
  ('nvlm-10', 'Frontier'),
  ('qwen2-vl', 'Frontier'),
  ('minicpm-v-26', 'Multimodal Model'),
  ('helios-video', 'Visual Generation'),
  ('deepseek-ocr', 'Frontier'),
  ('reconvla', 'World Model'),
  ('smolvla', 'World Model'),
  ('hunyuanvideo-avatar', 'Visual Generation'),
  ('vlm-3r', 'Multimodal Model'),
  ('vace-video', 'Visual Generation'),
  ('ui-tars-15', 'Multimodal Model'),
  ('skyreels-a2', 'Visual Generation'),
  ('stable-virtual-camera', 'Visual Generation'),
  ('videollama3', 'Multimodal Model'),
  ('jina-vlm', 'Multimodal Model'),
  ('ernie-image', 'Visual Generation'),
  ('loc3r-vlm', 'Multimodal Model'),
  ('qianfan-ocr', 'Multimodal Model'),
  ('hunyuanimage-30', 'Visual Generation'),
  ('ctrl-world-robot', 'World Model'),
  ('matrix-3d', 'Visual Generation'),
  ('step-audio2-mini', 'Multimodal Model'),
  ('voxtral', 'Multimodal Model'),
  ('cube-3d-roblox', 'Visual Generation'),
  ('hidream-o1-image', 'Visual Generation'),
  ('molmoact-2', 'World Model'),
  ('x-vla-soft-prompted', 'World Model'),
  ('glm-45v', 'Frontier'),
  ('omnigen2', 'Visual Generation'),
  ('show-o2', 'Multimodal Model'),
  ('magi-1-video', 'Visual Generation'),
  ('bagel-unified-multimodal', 'Frontier'),
  ('seed15-vl', 'Multimodal Model'),
  ('univla', 'World Model'),
  ('hidream-i1', 'Visual Generation'),
  ('step1x-edit', 'Visual Generation'),
  ('skyreels-v2', 'Visual Generation'),
  ('framepack-video', 'Visual Generation'),
  ('minimax-vl-01', 'Multimodal Model'),
  ('minicpm-o-45', 'Frontier'),
  ('pi07-physical-intelligence', 'World Model'),
  ('seedream-50-lite', 'Visual Generation'),
  ('qwen3-omni', 'Frontier'),
  ('gemini-25-flash-image', 'Visual Generation'),
  ('qwen-image-edit', 'Visual Generation'),
  ('wan22', 'Visual Generation'),
  ('flux-1-krea-dev', 'Visual Generation'),
  ('mistral-medium-3', 'Frontier'),
  ('pi05-physical-intelligence', 'World Model'),
  ('mistral-ocr', 'Multimodal Model'),
  ('aya-vision', 'Multimodal Model'),
  ('figure-helix', 'World Model'),
  ('firefly-video-model', 'Visual Generation'),
  ('gemini-20-flash', 'Multimodal Model'),
  ('genesis-embodied-ai', 'World Model'),
  ('pi0-physical-intelligence', 'World Model'),
  ('qwen3-vl', 'Multimodal Model'),
  ('openai-gpt-41-api', 'Multimodal Model'),
  ('janus-pro', 'Multimodal Model'),
  ('deepseek-vl2', 'Multimodal Model'),
  ('pixtral-large', 'Multimodal Model'),
  ('llava-onevision', 'Multimodal Model'),
  ('fastvlm', 'Multimodal Model'),
  ('movie-gen', 'Visual Generation'),
  ('veo-2-imagen-3-whisk', 'Visual Generation'),
  ('runway-gen-3-alpha', 'Visual Generation'),
  ('ideogram-3', 'Visual Generation'),
  ('hunyuan3d-2', 'Visual Generation'),
  ('cogvideox', 'Visual Generation'),
  ('gaia-2-world-model', 'World Model'),
  ('nvidia-gr00t-n1', 'World Model'),
  ('cosmos-transfer1', 'World Model'),
  ('diffusion-forcing-world-model', 'World Model'),
  ('project-genie-street-view', 'World Model'),
  ('worldlabs-spark-20', 'World Model'),
  ('worldlabs-3d-as-code', 'World Model'),
  ('phi-4-reasoning-vision', 'Multimodal Model'),
  ('gemini-robotics-on-device', 'Multimodal Model'),
  ('gemini-robotics', 'Multimodal Model'),
  ('gaia-3-world-model', 'World Model'),
  ('marble-world-model', 'World Model'),
  ('ltx-2-video-model', 'Visual Generation'),
  ('nvidia-cosmos-reason', 'World Model'),
  ('qwen-image-text-rendering', 'Visual Generation'),
  ('nvidia-cosmos-predict-2', 'World Model'),
  ('gemma-3n-preview', 'Multimodal Model'),
  ('adobe-firefly-creative-ai-2025', 'Visual Generation'),
  ('llama-4-multimodal', 'Multimodal Model'),
  ('smolvlm2-video-understanding', 'Multimodal Model'),
  ('runway-gwm-1', 'World Model'),
  ('stable-diffusion-35', 'Visual Generation'),
  ('ray-314-video-generation', 'Visual Generation'),
  ('sora-2', 'Visual Generation'),
  ('hunyuanworld-1', 'World Model'),
  ('genie-3-world-model', 'World Model'),
  ('seedance-1-video-generation', 'Visual Generation'),
  ('qwen25-omni', 'Multimodal Model'),
  ('gemini-25-thinking', 'Multimodal Model'),
  ('mistral-small-31', 'Multimodal Model'),
  ('wan-21-video-generation', 'Visual Generation'),
  ('internvl3', 'Multimodal Model'),
  ('kimi-vl', 'Multimodal Model'),
  ('hunyuanvideo', 'Visual Generation'),
  ('runway-gen-45', 'Visual Generation'),
  ('llama-32-vision', 'Multimodal Model'),
  ('recraft-v3', 'Visual Generation'),
  ('waymo-world-model', 'World Model'),
  ('v-jepa-2-world-model', 'World Model'),
  ('sora-world-simulators', 'World Model'),
  ('openai-4o-image-generation', 'Visual Generation'),
  ('sora-creating-video-from-text', 'Visual Generation'),
  ('runway-gen-4', 'Visual Generation'),
  ('flux-kontext', 'Visual Generation'),
  ('veo-3-imagen-4', 'Visual Generation'),
  ('mochi-1-open-video', 'Visual Generation'),
  ('qwen25-vl', 'Multimodal Model'),
  ('paligemma-2-mix', 'Multimodal Model'),
  ('gemma-3-multimodal', 'Multimodal Model'),
  ('siglip-2', 'Multimodal Model'),
  ('molmo-open-multimodal', 'Multimodal Model'),
  ('pixtral-12b', 'Multimodal Model'),
  ('nvidia-cosmos-world-foundation-models', 'World Model'),
  ('genie-2-world-model', 'World Model'),
  ('genie-generative-interactive-environments', 'World Model'),
  ('gaia-1-scaling', 'World Model'),
  ('clip-connecting-text-images', 'Multimodal Model'),
  ('blip-2', 'Multimodal Model'),
  ('stable-diffusion-3-medium', 'Visual Generation'),
  ('flux-1', 'Visual Generation'),
  ('veo-imagen-3', 'Visual Generation'),
  ('vlms-explained', 'Multimodal Model'),
  ('vision-language-pretraining', 'Multimodal Model'),
  ('illustrated-stable-diffusion', 'Visual Generation'),
  ('diffusion-models-lilian-weng', 'Visual Generation'),
  ('annotated-diffusion', 'Visual Generation'),
  ('world-models', 'World Model'),
  ('grasp-world-models', 'World Model'),
  ('othello-world-models', 'World Model'),
  ('hello-gpt-4o', 'Multimodal Model'),
  ('gemini-15-long-context', 'Multimodal Model'),
  ('palm-e-embodied-multimodal', 'Multimodal Model'),
  ('rt-2-vision-language-action', 'Multimodal Model'),
  ('flamingo-visual-language-model', 'Multimodal Model'),
  ('dalle-2', 'Visual Generation'),
  ('imagen-text-to-image', 'Visual Generation'),
  ('imagen-video', 'Visual Generation'),
  ('videopoet-zero-shot-video', 'Visual Generation'),
  ('stable-video-diffusion', 'Visual Generation'),
  ('muzero-learned-model-planning', 'World Model'),
  ('v-jepa-world-model', 'World Model'),
  ('sima-3d-virtual-environments', 'AI Agents'),
  ('gato-generalist-agent', 'AI Agents'),
  ('open-ended-play-agents', 'AI Agents'),
  ('claude-35-sonnet', 'Multimodal Model'),
  ('idefics2-vision-language-model', 'Multimodal Model'),
  ('paligemma-open-vlm', 'Multimodal Model'),
  ('florence-2-unified-vision', 'Multimodal Model'),
  ('sam-2-video-segmentation', 'Multimodal Model'),
  ('chameleon-mixed-modal', 'Multimodal Model'),
  ('make-a-video', 'Visual Generation'),
  ('emu-video-emu-edit', 'Visual Generation'),
  ('styledrop', 'Visual Generation'),
  ('sima-2-virtual-worlds', 'Frontier'),
  ('dreamerv2-discrete-world-models', 'World Model'),
  ('robocat-self-improving-agent', 'Frontier'),
  ('pali-language-image-learning', 'Multimodal Model'),
  ('kosmos-1-multimodal-llm', 'Multimodal Model'),
  ('kosmos-2-grounded-multimodal', 'Multimodal Model'),
  ('apple-mm1-multimodal-llm', 'Multimodal Model'),
  ('apple-ferret-refer-ground', 'Multimodal Model'),
  ('segment-anything-model', 'Multimodal Model'),
  ('fuyu-8b-multimodal', 'Multimodal Model'),
  ('dalle-3-chatgpt', 'Visual Generation'),
  ('sdxl-10-release', 'Visual Generation'),
  ('phenaki-text-to-video', 'Visual Generation'),
  ('magic3d-text-to-3d', 'Visual Generation'),
  ('parti-text-to-image', 'Visual Generation'),
  ('efficientzero-limited-data', 'World Model'),
  ('iris-transformer-world-models', 'World Model'),
  ('i-jepa-human-like-ai', 'World Model'),
  ('qwen-vl-visual-language', 'Frontier'),
  ('cogvlm-visual-expert', 'Multimodal Model'),
  ('llava-next-reasoning-ocr', 'Multimodal Model'),
  ('screenai-ui-infographics', 'Multimodal Model'),
  ('donut-ocr-free-document-understanding', 'Multimodal Model'),
  ('imagen-editor-editbench', 'Visual Generation'),
  ('ediff-i-ensemble-denoisers', 'Visual Generation'),
  ('deepfloyd-if-text-rendering', 'Visual Generation'),
  ('t2i-adapter-controllable-generation', 'Visual Generation'),
  ('openai-vpt-video-pretraining', 'AI Agents'),
  ('rt-1-robotics-transformer', 'Frontier'),
  ('decision-transformer-sequence-rl', 'AI Agents')
)
update public.blogs as blog
set
  category = updates.category,
  updated_at = now()
from updates
where blog.id = updates.id
  and blog.category is distinct from updates.category;

-- Normalize any extra remote rows, drafts, or legacy categories before re-adding the check.
update public.blogs
set
  category = case
    when category = 'Frontier Developments' then 'Frontier'
    when category in ('Research Experience', 'Research Experiences') then 'Research Craft'
    else 'Research Craft'
  end,
  updated_at = now()
where category not in (
  'Foundation Model',
  'LLM & MLLM',
  'Multimodal Model',
  'Visual Generation',
  'World Model',
  'AI Agents',
  'Efficient AI',
  'Trustworthy AI',
  'Research Craft',
  'Frontier',
  'How to Research'
);

-- Re-add the current BlogrXiv taxonomy constraint after all rows are valid.
alter table public.blogs
add constraint blogs_category_check
check (category in (
  'Foundation Model',
  'LLM & MLLM',
  'Multimodal Model',
  'Visual Generation',
  'World Model',
  'AI Agents',
  'Efficient AI',
  'Trustworthy AI',
  'Research Craft',
  'Frontier',
  'How to Research'
));

commit;

-- Verification
select count(*) as published_count
from public.blogs
where status = 'published';

select category, count(*)
from public.blogs
where status = 'published'
group by category
order by category;
