-- One selected blog from each category that was not already represented in the project.
insert into public.blogs (id,title,excerpt,author,author_avatar,category,tags,read_time,publish_date,source_name,url,cover_image,cover_alt,cover_fit,status,featured) values
('codelion-1-billion-token-challenge','The 1 Billion Token Challenge: Finding the Perfect Pre-training Mix','CodeLion reports more than 50 controlled experiments on data mixtures and curriculum strategies for pre-training, releasing the recipes and artifacts behind a one-billion-token challenge.','Asankhaya Sharma / CodeLion','https://www.google.com/s2/favicons?domain=huggingface.co&sz=128','Foundation Model',array['Pre-training','Data Mixtures','Language Models','Open Research'],'12 min read','2025-11-03','Hugging Face Blog','https://huggingface.co/blog/codelion/optimal-dataset-mixing','','The 1 Billion Token Challenge article cover','cover','published',false),
('hugging-face-mixture-of-experts-explained','Mixture of Experts Explained','Hugging Face explains the core ideas behind mixture-of-experts language models, including sparse routing, expert capacity, load balancing, and the trade-offs of scaling conditional computation.','Hugging Face','https://www.google.com/s2/favicons?domain=huggingface.co&sz=128','LLM & MLLM',array['Mixture of Experts','Sparse Models','Transformers','Model Architecture'],'10 min read','2023-01-01','Hugging Face Blog','https://huggingface.co/blog/moe','','Mixture of Experts Explained article cover','cover','published',false),
('nvidia-vila-visual-language-models','Visual Language Models on NVIDIA Hardware with VILA','NVIDIA and MIT introduce VILA and walk through visual-language model training, multi-image and video question answering, and efficient AWQ deployment on NVIDIA hardware.','NVIDIA & MIT','https://www.google.com/s2/favicons?domain=nvidia.com&sz=128','Multimodal Model',array['VILA','Vision Language Models','Video Understanding','AWQ'],'9 min read','2024-05-03','NVIDIA Technical Blog','https://developer.nvidia.com/blog/visual-language-models-on-nvidia-hardware-with-vila/','','VILA visual language model article cover','cover','published',false),
('meta-open-sourcing-touch-representations-robot-dexterity','Open-Sourcing Touch Representations and Models for Robot Dexterity','Meta AI open-sources touch representations and models that help robots perceive contact and improve dexterous manipulation, expanding the foundation-model toolkit for embodied intelligence.','Meta AI','https://www.google.com/s2/favicons?domain=ai.meta.com&sz=128','World Model',array['Robotics','Tactile Sensing','Dexterous Manipulation','Embodied AI'],'8 min read','2025-01-01','Meta AI','https://ai.meta.com/blog/fair-robotics-open-source/','','Robot dexterity article cover','cover','published',false),
('anthropic-quantifying-infrastructure-noise-agentic-coding-evals','Quantifying Infrastructure Noise in Agentic Coding Evals','Anthropic quantifies how CPU, memory, storage, and network quotas change coding-agent evaluation scores, showing why infrastructure must be reported as an evaluation variable.','Anthropic / Gian Segato','https://www.google.com/s2/favicons?domain=anthropic.com&sz=128','AI Agents',array['Coding Agents','Evaluation','Infrastructure','Reproducibility'],'10 min read','2026-02-05','Anthropic Engineering','https://www.anthropic.com/engineering/infrastructure-noise','','Infrastructure noise in agentic coding evaluations article cover','cover','published',false),
('ibm-research-artificial-intelligence','IBM Research — Artificial Intelligence','IBM Research''s artificial-intelligence index brings together work across foundation models, reasoning, AI for science, chips, and enterprise AI, providing a broad view of frontier research directions.','IBM Research','https://www.google.com/s2/favicons?domain=ibm.com&sz=128','Frontier',array['Frontier AI','AI Research','Foundation Models','AI for Science'],'8 min read','2026-07-26','IBM Research','https://research.ibm.com/blog?tag=artificial-intelligence','','IBM Research artificial intelligence article cover','cover','published',false)
on conflict (id) do update set title=excluded.title,excerpt=excluded.excerpt,author=excluded.author,author_avatar=excluded.author_avatar,category=excluded.category,tags=excluded.tags,read_time=excluded.read_time,publish_date=excluded.publish_date,source_name=excluded.source_name,url=excluded.url,cover_image=excluded.cover_image,cover_alt=excluded.cover_alt,cover_fit=excluded.cover_fit,status=excluded.status,featured=excluded.featured;
